class Game:
    def __init__(self, row: list):
        itr = iter(row)

        self.season_id = next(itr)
        self.team_id = next(itr)
        self.team_abbreviation = next(itr)
        self.team_name = next(itr)
        self.game_id = next(itr)
        self.game_date = next(itr)
        self.matchup = next(itr)
        self.wl = next(itr)
        self.minutes = next(itr)
        self.points = next(itr)
        self.fgm = next(itr)
        self.fga = next(itr)
        self.fg_pct = next(itr)
        self.fg3m = next(itr)
        self.fg3a = next(itr)
        self.fg3_pct = next(itr)
        self.ftm = next(itr)
        self.fta = next(itr)
        self.ft_pct = next(itr)
        self.oreb = next(itr)
        self.dreb = next(itr)
        self.reb = next(itr)
        self.ast = next(itr)
        self.stl = next(itr)
        self.blk = next(itr)
        self.tov = next(itr)
        self.pf = next(itr)
        self.plus_minus = next(itr)
